spring:
  kafka:
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: movie-consumer
      bootstrap-servers: localhost:9093
      topic-name: kafka_example_movie_avro
      properties:
        auto.register.schemas: false
        specific.avro.reader: true
        schema.registry.url: http://localhost:8181
    listener:
      ack-mode: manual_immediate

kafka-consumer:
  retry-initial-interval: 1000
  retry-multiplier: 2
  retry-max-interval: 300000
