services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9094:9094
    environment:
     KAFKA_PROCESS_ROLES: controller,broker
     KAFKA_NODE_ID: 1
     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
     KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
     KAFKA_LOG_DIRS: /var/lib/kafka/data
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_LOG_RETENTION_HOURS: 168
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     CLUSTER_ID: local-kafka-cluster
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      - kafka
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 256M

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - 8181:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_AUTO_REGISTER_SCHEMAS: false
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      - kafka
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 256M
    depends_on:
      kafka:
        condition: service_healthy

  init-kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./avro:/opt/docker/avro
    networks:
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      ub kafka-ready -b kafka:9092 1 60
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic kafka_example_movie_avro --replication-factor 1 --partitions 6

      ub sr-ready schema-registry 8081 60
      if [[ \\
        `curl --write-out '%{http_code}' --silent --output /dev/null \\
          --request GET http://schema-registry:8081/subjects/kafka_example_movie_avro-key/versions \\
          --header 'Accept: application/vnd.schemaregistry.v1+json'` \\
        == 404 ]]; then
        curl --request POST http://schema-registry:8081/subjects/kafka_example_movie_avro-key/versions \\
          --header 'Accept: application/vnd.schemaregistry.v1+json' \\
          --header 'Content-Type: application/json' \\
            --data-binary @/opt/docker/avro/movie_key.json
      fi
      if [[ \\
        `curl --write-out '%{http_code}' --silent --output /dev/null \\
          --request GET http://schema-registry:8081/subjects/kafka_example_movie_avro-value/versions \\
          --header 'Accept: application/vnd.schemaregistry.v1+json'` \\
        == 404 ]]; then
        curl --request POST http://schema-registry:8081/subjects/kafka_example_movie_avro-value/versions \\
          --header 'Accept: application/vnd.schemaregistry.v1+json' \\
          --header 'Content-Type: application/json' \\
          --data-binary @/opt/docker/avro/movie_value.json
      fi
      "

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 9090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    links:
      - kafka
      - schema-registry
    networks:
      - kafka
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 256M
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy

networks:
  kafka:
    name: kafka
